# Last Call — hand-authored Solarized-influenced palette

[colors-dark]
alpha=0.85
foreground=94b3b5
background=0b1d20
selection-foreground=c8e3e2
selection-background=42686f
cursor=0b1d20 e0f5f2

regular0=0b1d20
regular1=ed634c
regular2=58ad73
regular3=c5c15a
regular4=668ca9
regular5=9c8499
regular6=00c6c2
regular7=94b3b5

bright0=42686f
bright1=f47a64
bright2=7ac48e
bright3=d8d373
bright4=83a6be
bright5=b49eb0
bright6=42d8d2
bright7=e0f5f2
